-- Add all missing columns for initiatives, activities, and payments tables

-- ===== INITIATIVES table =====
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS responsible_person TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS contact_info TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS goals JSONB DEFAULT '[]';
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS achievements JSONB DEFAULT '[]';
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS challenges JSONB DEFAULT '[]';
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS resources_needed JSONB DEFAULT '[]';
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS partner_organizations JSONB DEFAULT '[]';
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS media_links JSONB DEFAULT '[]';
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS target_amount NUMERIC;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS collected_amount NUMERIC DEFAULT 0;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS donation_count INTEGER DEFAULT 0;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS min_contribution NUMERIC;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS max_contribution NUMERIC;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS start_date_hijri TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS end_date_hijri TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS created_by UUID;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS archived_by UUID;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS completion_notes TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS title_ar TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS description_ar TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS beneficiary_name_ar TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS beneficiary_name_en TEXT;

-- ===== ACTIVITIES table =====
ALTER TABLE activities ADD COLUMN IF NOT EXISTS beneficiary_contact TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS beneficiary_notes_ar TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS beneficiary_notes_en TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS current_amount NUMERIC DEFAULT 0;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS collection_start_date DATE;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS collection_end_date DATE;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS collection_deadline DATE;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS event_date DATE;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS event_time TIME;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS event_location_ar TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS event_location_en TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS max_attendees INTEGER;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS registration_fee NUMERIC DEFAULT 0;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS organizer_id UUID;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS financial_manager_id UUID;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS co_organizers JSONB;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS collection_status TEXT DEFAULT 'pending';
ALTER TABLE activities ADD COLUMN IF NOT EXISTS completion_percentage NUMERIC DEFAULT 0;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS show_beneficiary BOOLEAN DEFAULT true;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS allow_anonymous_contributions BOOLEAN DEFAULT true;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS requires_registration BOOLEAN DEFAULT false;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS registration_deadline DATE;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS urgency_level INTEGER DEFAULT 3;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS internal_notes TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS public_notes_ar TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS public_notes_en TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS supporting_documents JSONB;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS images JSONB;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS contribution_count INTEGER DEFAULT 0;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS contributor_count INTEGER DEFAULT 0;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS published_at TIMESTAMP;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS hijri_start_date TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS hijri_end_date TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS hijri_year INTEGER;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS hijri_month INTEGER;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS activity_type TEXT;

-- ===== PAYMENTS table =====
ALTER TABLE payments ADD COLUMN IF NOT EXISTS reference_number TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS processed_by UUID;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS hijri_date_string TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS hijri_year INTEGER;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS hijri_month INTEGER;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS hijri_day INTEGER;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS hijri_month_name TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS import_year INTEGER;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS excel_import_batch TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_id UUID;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS notes_ar TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS notes_en TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS months_purchased INTEGER DEFAULT 1;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS receipt_number TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS transaction_id TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS processing_notes TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS is_on_behalf BOOLEAN DEFAULT false;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS bank_name TEXT;

SELECT 'All missing columns added!' as result;
