export const ARABIC_LABELS = {
  // Navigation
  dashboard: 'الرئيسية',
  activities: 'الأنشطة',
  members: 'الأعضاء',
  contributions: 'المساهمات',
  reports: 'التقارير',
  settings: 'الإعدادات',
  logout: 'تسجيل الخروج',

  // Dashboard
  totalActivities: 'إجمالي الأنشطة',
  totalMembers: 'إجمالي الأعضاء',
  totalContributions: 'إجمالي المساهمات',
  pendingApprovals: 'في انتظار الموافقة',
  monthlyRevenue: 'الإيرادات الشهرية',
  activeMembers: 'الأعضاء النشطين',

  // Activities
  familyOccasions: 'المناسبات العائلية',
  charitableInitiatives: 'المبادرات الخيرية',
  diyasAndCompensations: 'الديات والتعويضات',
  addNewActivity: 'إضافة نشاط جديد',
  editActivity: 'تعديل النشاط',
  deleteActivity: 'حذف النشاط',
  approveActivity: 'الموافقة على النشاط',
  rejectActivity: 'رفض النشاط',

  // Members
  addNewMember: 'إضافة عضو جديد',
  editMember: 'تعديل العضو',
  deleteMember: 'حذف العضو',
  memberRole: 'دور العضو',
  memberStatus: 'حالة العضو',
  lastLogin: 'آخر تسجيل دخول',

  // Contributions
  approveContribution: 'الموافقة على المساهمة',
  rejectContribution: 'رفض المساهمة',
  paymentMethod: 'طريقة الدفع',
  contributionAmount: 'مبلغ المساهمة',
  contributionDate: 'تاريخ المساهمة',

  // Common
  save: 'حفظ',
  cancel: 'إلغاء',
  edit: 'تعديل',
  delete: 'حذف',
  view: 'عرض',
  search: 'بحث',
  filter: 'تصفية',
  export: 'تصدير',
  print: 'طباعة',
  refresh: 'تحديث',
  loading: 'جاري التحميل...',
  error: 'خطأ',
  success: 'نجح',
  warning: 'تحذير',
  info: 'معلومات',

  // Forms
  required: 'مطلوب',
  email: 'البريد الإلكتروني',
  phone: 'رقم الهاتف',
  name: 'الاسم',
  description: 'الوصف',
  date: 'التاريخ',
  amount: 'المبلغ',
  status: 'الحالة',

  // Status
  active: 'نشط',
  inactive: 'غير نشط',
  pending: 'معلق',
  approved: 'موافق عليه',
  rejected: 'مرفوض',
  completed: 'مكتمل',
  cancelled: 'ملغي',

  // Roles
  superAdmin: 'مدير عام',
  admin: 'مدير',
  financialManager: 'مدير مالي',
  organizer: 'منظم',
  member: 'عضو',

  // Payments
  payments: 'المدفوعات',
  paymentsOverview: 'نظرة عامة على المدفوعات',
  createPayment: 'إنشاء دفعة جديدة',
  paymentDetails: 'تفاصيل الدفع',
  paymentHistory: 'تاريخ المدفوعات',
  paymentReference: 'رقم المرجع',
  totalPayments: 'إجمالي المدفوعات',
  pendingPayments: 'المدفوعات المعلقة',
  overduePayments: 'المدفوعات المتأخرة',
  totalRevenue: 'إجمالي الإيرادات',
  paymentCategory: 'فئة الدفع',
  paymentType: 'نوع الدفع',
  dueDate: 'تاريخ الاستحقاق',
  paidDate: 'تاريخ الدفع',
  approvePayment: 'الموافقة على الدفع',
  rejectPayment: 'رفض الدفع',
  refundPayment: 'استرداد الدفع',
  generateReceipt: 'إنشاء إيصال',
  printReceipt: 'طباعة الإيصال',
  paymentApproved: 'تمت الموافقة على الدفع',
  paymentRejected: 'تم رفض الدفع',
  paymentRefunded: 'تم استرداد الدفع',
  subscriptionPayment: 'دفع اشتراك',
  activityPayment: 'دفع نشاط',
  membershipFee: 'رسوم العضوية',
  donationPayment: 'دفع تبرع',

  // Payment Methods
  cash: 'نقدي',
  bankTransfer: 'حوالة بنكية',
  appPayment: 'دفع إلكتروني',
  digitalWallet: 'محفظة رقمية',
  creditCard: 'بطاقة ائتمان',
  debitCard: 'بطاقة مدين',
  check: 'شيك',

  // Validation Messages
  fieldRequired: 'هذا الحقل مطلوب',
  invalidEmail: 'البريد الإلكتروني غير صحيح',
  invalidPhone: 'رقم الهاتف غير صحيح',
  passwordTooShort: 'كلمة المرور قصيرة جداً',
  amountTooLow: 'المبلغ أقل من الحد الأدنى (50 ريال)',

  // Success Messages
  activityCreated: 'تم إنشاء النشاط بنجاح',
  memberAdded: 'تم إضافة العضو بنجاح',
  contributionApproved: 'تم الموافقة على المساهمة',
  dataExported: 'تم تصدير البيانات بنجاح',

  // Error Messages
  networkError: 'خطأ في الاتصال',
  serverError: 'خطأ في الخادم',
  unauthorized: 'غير مصرح',
  forbidden: 'ممنوع',
  notFound: 'غير موجود',

  // Occasions
  occasions: 'المناسبات',
  occasionsOverview: 'نظرة عامة على المناسبات',
  createOccasion: 'إنشاء مناسبة جديدة',
  occasionDetails: 'تفاصيل المناسبة',
  occasionCalendar: 'تقويم المناسبات',
  occasionType: 'نوع المناسبة',
  occasionLocation: 'مكان المناسبة',
  occasionTime: 'وقت المناسبة',
  rsvp: 'تأكيد الحضور',
  rsvpManagement: 'إدارة تأكيد الحضور',
  attendees: 'الحضور',
  confirmed: 'مؤكد',
  declined: 'معتذر',
  maybe: 'ربما',
  wedding: 'زفاف',
  birth: 'ولادة',
  graduation: 'تخرج',
  celebration: 'احتفال',
  conference: 'مؤتمر',
  meeting: 'اجتماع',

  // Initiatives
  initiatives: 'المبادرات',
  initiativesOverview: 'نظرة عامة على المبادرات',
  createInitiative: 'إنشاء مبادرة جديدة',
  initiativeDetails: 'تفاصيل المبادرة',
  initiativeCategories: 'فئات المبادرات',
  initiativeProgress: 'تقدم المبادرة',
  targetAmount: 'المبلغ المستهدف',
  raisedAmount: 'المبلغ المجمع',
  contribution: 'المساهمة',
  contribute: 'ساهم',
  minimumContribution: 'الحد الأدنى للمساهمة (50 ريال)',
  education: 'التعليم',
  health: 'الصحة',
  charity: 'الخير',
  community: 'المجتمع',
  environment: 'البيئة',
  technology: 'التكنولوجيا',

  // Diyas
  diyas: 'الديات',
  diyasOverview: 'نظرة عامة على الديات',
  createDiya: 'إنشاء دية جديدة',
  diyaDetails: 'تفاصيل الدية',
  diyaStatus: 'حالة الدية',
  caseDetails: 'تفاصيل القضية',
  compensationAmount: 'مبلغ التعويض',
  minimumDiya: 'الحد الأدنى للدية (50 ريال)',
  caseType: 'نوع القضية',
  accidentalDamage: 'ضرر عارض',
  intentionalDamage: 'ضرر مقصود',
  medicalCompensation: 'تعويض طبي',
  propertyDamage: 'ضرر في الممتلكات',
  resolved: 'تم الحل',
  investigating: 'قيد التحقيق',
  awaitingPayment: 'في انتظار الدفع',

  // Notifications
  notifications: 'الإشعارات',
  notificationsCenter: 'مركز الإشعارات',
  createNotification: 'إنشاء إشعار جديد',
  notificationDetails: 'تفاصيل الإشعار',
  notificationFilters: 'مرشحات الإشعارات',
  unreadNotifications: 'الإشعارات غير المقروءة',
  markAsRead: 'تحديد كمقروء',
  markAllAsRead: 'تحديد الكل كمقروء',
  notificationType: 'نوع الإشعار',
  notificationPriority: 'أولوية الإشعار',
  sendToAll: 'إرسال للجميع',
  sendToGroup: 'إرسال للمجموعة',
  general: 'عام',
  urgent: 'عاجل',
  reminder: 'تذكير',
  announcement: 'إعلان',
  high: 'عالية',
  medium: 'متوسطة',
  low: 'منخفضة',
  read: 'مقروء',
  unread: 'غير مقروء',

  // Calendar
  calendar: 'التقويم',
  hijriDate: 'التاريخ الهجري',
  gregorianDate: 'التاريخ الميلادي',
  today: 'اليوم',
  tomorrow: 'غداً',
  thisWeek: 'هذا الأسبوع',
  thisMonth: 'هذا الشهر',
  nextMonth: 'الشهر القادم',

  // Progress and Stats
  progress: 'التقدم',
  percentage: 'النسبة المئوية',
  goal: 'الهدف',
  achieved: 'تم تحقيقه',
  remaining: 'المتبقي',
  contributors: 'المساهمون',
  totalContributors: 'إجمالي المساهمين',
  averageContribution: 'متوسط المساهمة',
};

export const CURRENCY = {
  symbol: 'ر.س',
  code: 'SAR',
  name: 'ريال سعودي'
};

export const HIJRI_MONTHS = [
  'محرم', 'صفر', 'ربيع الأول', 'ربيع الثاني',
  'جمادى الأولى', 'جمادى الثانية', 'رجب', 'شعبان',
  'رمضان', 'شوال', 'ذو القعدة', 'ذو الحجة'
];