-- Harden initiative contributions from native mobile clients.
-- 1. One client_request_id per member makes retries idempotent.
-- 2. receipt_document_id links the uploaded receipt to Documents/Admin.
-- 3. Both the current initiatives table and the legacy activities table are
--    supported because the public /api/initiatives feed currently merges them.

BEGIN;

CREATE TABLE IF NOT EXISTS activity_contributions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  member_id UUID NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  payment_method VARCHAR(50) NOT NULL DEFAULT 'bank_transfer',
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  reference_number VARCHAR(50),
  notes TEXT,
  client_request_id UUID,
  receipt_document_id UUID REFERENCES documents_metadata(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS activity_contributions
  ADD COLUMN IF NOT EXISTS client_request_id UUID,
  ADD COLUMN IF NOT EXISTS receipt_document_id UUID
    REFERENCES documents_metadata(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_activity_contributions_member_request
  ON activity_contributions(member_id, client_request_id)
  WHERE client_request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_activity_contributions_receipt_document
  ON activity_contributions(receipt_document_id)
  WHERE receipt_document_id IS NOT NULL;

ALTER TABLE IF EXISTS initiative_donations
  ADD COLUMN IF NOT EXISTS client_request_id UUID,
  ADD COLUMN IF NOT EXISTS receipt_url TEXT,
  ADD COLUMN IF NOT EXISTS receipt_document_id UUID
    REFERENCES documents_metadata(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS approved_by UUID
    REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS approval_date TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS uq_initiative_donations_member_request
  ON initiative_donations(member_id, client_request_id)
  WHERE client_request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_initiative_donations_receipt_document
  ON initiative_donations(receipt_document_id)
  WHERE receipt_document_id IS NOT NULL;

COMMENT ON COLUMN activity_contributions.client_request_id IS
  'Stable UUID generated by the mobile client; prevents duplicate contributions on retry.';
COMMENT ON COLUMN activity_contributions.receipt_document_id IS
  'Receipt file metadata linked to this contribution.';
COMMENT ON COLUMN initiative_donations.client_request_id IS
  'Stable UUID generated by the mobile client; prevents duplicate contributions on retry.';
COMMENT ON COLUMN initiative_donations.receipt_document_id IS
  'Receipt file metadata linked to this contribution.';

-- Keep both legacy collected_amount and the mobile-facing current_amount in
-- sync with approved donations. Recalculation makes status changes idempotent
-- and also handles rejection/deletion without double counting.
CREATE OR REPLACE FUNCTION update_initiative_amount()
RETURNS TRIGGER AS $$
DECLARE
  target_initiative_id UUID;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_initiative_id := OLD.initiative_id;
  ELSE
    target_initiative_id := NEW.initiative_id;
  END IF;

  UPDATE initiatives i
     SET collected_amount = totals.amount,
         current_amount = totals.amount,
         updated_at = NOW()
    FROM (
      SELECT COALESCE(SUM(d.amount), 0) AS amount
        FROM initiative_donations d
       WHERE d.initiative_id = target_initiative_id
         AND d.status IN ('completed', 'approved', 'confirmed')
    ) totals
   WHERE i.id = target_initiative_id;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_initiative_amount_trigger ON initiative_donations;
CREATE TRIGGER update_initiative_amount_trigger
AFTER INSERT OR UPDATE OR DELETE ON initiative_donations
FOR EACH ROW EXECUTE FUNCTION update_initiative_amount();

UPDATE initiatives i
   SET collected_amount = totals.amount,
       current_amount = totals.amount,
       updated_at = NOW()
  FROM (
    SELECT d.initiative_id AS id,
           COALESCE(SUM(d.amount) FILTER (
             WHERE d.status IN ('completed', 'approved', 'confirmed')
           ), 0) AS amount
      FROM initiative_donations d
     GROUP BY d.initiative_id
  ) totals
 WHERE i.id = totals.id;

COMMIT;
